name: Run All Tests

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.18

      - name: Install Dependencies
        run: npm ci

      - name: Build with Firebase API Keys
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.AIzaSyAg__3UrL0_d2NeoVDce0CxlJOaQYkbTIk }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.budgetbyte-d5bf8.firebaseapp.com }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.budgetbyte-d5bf8 }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.budgetbyte-d5bf8.appspot.com }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.386914039894 }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.1:386914039894:web:312390060d4abd98e3e3f7 }}
        run: npm run build
      - name: Run tests
        run: npm test
